version: "3"

services:
  mongodb:
    container_name: mongo-udemy
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27018:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
